import { useMemo, useState } from 'react';
import { BarChart3, Check, ChevronLeft, ChevronRight, CircleHelp, Clock3, FileSpreadsheet, LayoutDashboard, ListChecks, LogOut, Menu, Plus, Search, Settings2, ShieldCheck, Trophy, Users, Vote, X } from 'lucide-react';
import { auditEvents, candidates, students as seedStudents, type Student } from './data';
import { Badge, Button, CandidateCard, CategoryHeader, Countdown, EmptyState, Field, FileDrop, Footer, LivePill, Logo, Modal, Notice, PageShell, Progress, RosterRow, StatCard, TopNav } from './components';

type View = 'home' | 'ballot' | 'success' | 'admin-login' | 'admin';
type AdminPage = 'Overview' | 'Students' | 'Create Room' | 'Candidates' | 'Results' | 'Audit Log';

type Toast = { message: string; tone: 'ok' | 'error' } | null;

export default function App() {
  const [view, setView] = useState<View>('home');
  const [adminPage, setAdminPage] = useState<AdminPage>('Overview');
  const [students, setStudents] = useState<Student[]>(seedStudents);
  const [roll, setRoll] = useState('');
  const [cnic, setCnic] = useState('');
  const [cr, setCr] = useState('');
  const [gr, setGr] = useState('');
  const [modal, setModal] = useState<'login' | 'confirm' | 'help' | null>(null);
  const [toast, setToast] = useState<Toast>(null);
  const [adminEmail, setAdminEmail] = useState('');
  const [adminLoading, setAdminLoading] = useState(false);
  const [adminError, setAdminError] = useState('');
  const [adminPassword, setAdminPassword] = useState('');
  const [query, setQuery] = useState('');
  const [csvName, setCsvName] = useState('');
  const [mobileNav, setMobileNav] = useState(false);

  const notify = (message: string, tone: Toast['tone'] = 'ok') => {
    setToast({ message, tone });
    window.setTimeout(() => setToast(null), 3500);
  };

  const verifyVoter = () => {
    const normalizedRoll = roll.trim().toUpperCase();
    const normalizedCnic = cnic.replace(/\D/g, '');
    const voter = students.find(s => s.roll === normalizedRoll && s.cnic.replace(/\D/g, '') === normalizedCnic);
    if (!normalizedRoll || !normalizedCnic) return notify('Enter both your Roll Number and CNIC.', 'error');
    if (!voter || !voter.eligible) return notify('We could not verify an eligible voter with those details.', 'error');
    if (voter.voted) return notify('This voter has already completed the ballot.', 'error');
    setModal(null); setView('ballot');
  };

  const submitVote = () => {
    if (!cr || !gr) return;
    setStudents(items => items.map(s => s.roll === roll.trim().toUpperCase() ? { ...s, voted: true } : s));
    setModal(null); setView('success');
    notify('Ballot recorded successfully.');
  };

  const loginAdmin = async () => {
    setAdminError('');
    if (!adminEmail.trim() || !adminPassword) return setAdminError('Enter your administrator email and password.');
    setAdminLoading(true);
    try {
      const response = await fetch('/api/admin-login', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: adminEmail.trim(), password: adminPassword }) });
      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(data.error || 'Unable to sign in.');
      setAdminPassword(''); setView('admin'); notify('Administrator session started.');
    } catch (error) {
      setAdminError(error instanceof Error ? error.message : 'Unable to sign in.');
    } finally { setAdminLoading(false); }
  };

  const logoutAdmin = async () => {
    await fetch('/api/admin-logout', { method: 'POST', credentials: 'include' }).catch(() => undefined);
    setView('home'); setAdminPage('Overview'); setAdminEmail(''); notify('Signed out.');
  };

  const openAdmin = async () => {
    setAdminError(''); setView('admin-login');
    try {
      const response = await fetch('/api/admin-session', { credentials: 'include' });
      const data = await response.json();
      if (data.authenticated) { setAdminEmail(data.email || 'Administrator'); setView('admin'); }
    } catch { /* Unauthenticated visitors stay on the login screen. */ }
  };

  if (view === 'admin-login') return <AdminLogin email={adminEmail} password={adminPassword} error={adminError} loading={adminLoading} onEmail={setAdminEmail} onPassword={setAdminPassword} onSubmit={loginAdmin} onBack={() => setView('home')} />;
  if (view === 'admin') return <AdminShell page={adminPage} setPage={setAdminPage} students={students} setStudents={setStudents} query={query} setQuery={setQuery} csvName={csvName} setCsvName={setCsvName} mobileNav={mobileNav} setMobileNav={setMobileNav} adminEmail={adminEmail} onLogout={logoutAdmin} onBack={() => setView('home')} />;

  return <div className="min-h-screen bg-canvas text-ink">
    <TopNav onAdmin={openAdmin} onHelp={() => setModal('help')} />
    {view === 'home' && <Home onStart={() => setModal('login')} onHelp={() => setModal('help')} />}
    {view === 'ballot' && <Ballot cr={cr} gr={gr} setCr={setCr} setGr={setGr} onBack={() => setView('home')} onReview={() => setModal('confirm')} />}
    {view === 'success' && <Success onDone={() => { setView('home'); setRoll(''); setCnic(''); setCr(''); setGr(''); }} />}
    <Footer />
    {toast && <div className={`fixed bottom-4 left-4 right-4 z-[60] mx-auto flex max-w-md items-center gap-3 rounded-2xl px-4 py-3 text-sm font-bold text-white shadow-soft ${toast.tone === 'error' ? 'bg-red-600' : 'bg-ink'}`} role="status"><Check size={16}/>{toast.message}<button className="ml-auto opacity-70" onClick={() => setToast(null)} aria-label="Dismiss notification"><X size={16}/></button></div>}
    {modal === 'login' && <Modal title="Verify your identity" description="Your Roll Number and CNIC must match the registered voter roster." onClose={() => setModal(null)}><div className="grid gap-4"><Field label="Roll Number" value={roll} onChange={e => setRoll(e.target.value)} placeholder="e.g. BSCS-001" autoComplete="off"/><Field label="CNIC Number" value={cnic} onChange={e => setCnic(e.target.value)} placeholder="Enter 13-digit CNIC" inputMode="numeric" autoComplete="off"/><Notice>Identity verification only checks eligibility. A production ballot store should keep voter identity separate from ballot choices.</Notice><Button className="w-full" onClick={verifyVoter}>Verify & continue <ChevronRight size={16}/></Button></div></Modal>}
    {modal === 'confirm' && <Modal title="Review your ballot" description="Confirm both choices before final submission. Votes cannot be changed afterwards." onClose={() => setModal(null)}><div className="grid gap-3"><Review label="CR · Class Representative" value={candidates.find(c => c.id === cr)?.name || 'Not selected'}/><Review label="GR · General Representative" value={candidates.find(c => c.id === gr)?.name || 'Not selected'}/><div className="grid grid-cols-2 gap-2 pt-2"><Button variant="secondary" onClick={() => setModal(null)}>Go back</Button><Button disabled={!cr || !gr} onClick={submitVote}>Submit <Check size={15}/></Button></div></div></Modal>}
    {modal === 'help' && <Modal title="How voting works" description="Three simple steps from verification to submission." onClose={() => setModal(null)}><div className="grid gap-4"><HelpStep n="01" title="Verify" text="Enter the Roll Number and CNIC registered for your student record."/><HelpStep n="02" title="Choose" text="Select exactly one Class Representative and one General Representative."/><HelpStep n="03" title="Submit" text="Review your selections and submit a final ballot."/></div></Modal>}
  </div>;
}

function Home({ onStart, onHelp }: { onStart: () => void; onHelp: () => void }) {
  return <main>
    <section className="relative overflow-hidden"><div className="absolute inset-x-0 top-0 -z-10 h-[620px] bg-[radial-gradient(circle_at_75%_20%,rgba(23,92,211,.15),transparent_34%),linear-gradient(180deg,#fff_0%,#f8fafc_100%)]"/><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-14 sm:px-6 sm:py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24"><div><LivePill/><h1 className="mt-6 max-w-3xl text-5xl font-black tracking-[-.045em] text-ink sm:text-6xl lg:text-7xl">Your voice.<br/><span className="text-brand">Your choice.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-muted sm:text-lg">A focused student election experience built around verified access, clear choices and a privacy-first ballot journey.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button className="px-6" onClick={onStart}>Enter ballot <ChevronRight size={17}/></Button><Button variant="ghost" onClick={onHelp}>How voting works <CircleHelp size={17}/></Button></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-xs font-bold text-muted"><span className="flex items-center gap-2"><ShieldCheck size={15} className="text-mint"/> Verified access</span><span className="flex items-center gap-2"><Vote size={15} className="text-brand"/> One-time ballot</span><span className="flex items-center gap-2"><Clock3 size={15}/> Fast & simple</span></div></div><HeroPreview/></div></section>
    <section className="border-y border-line bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 px-4 py-8 sm:px-6 md:grid-cols-4 lg:px-8"><Metric value="500" label="Registered students"/><Metric value="470" label="Eligible voters"/><Metric value="2" label="Choices per voter"/><Metric value="100%" label="Admin controlled"/></div></section>
    <section id="how" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><SectionTitle eyebrow="Simple by design" title="A voting flow that gets out of the way." text="Every screen has one job, so students can finish confidently without learning a complicated system."/><div className="mt-10 grid gap-4 md:grid-cols-3"><Feature n="01" title="Verify" text="Match Roll Number and CNIC against the registered roster before entering the ballot."/><Feature n="02" title="Choose" text="Pick one candidate from each configured representative category."/><Feature n="03" title="Submit" text="Review both selections once, then cast a final one-time ballot."/></div></section>
    <section id="security" className="bg-ink text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8 lg:py-24"><div><Badge tone="blue">PRIVACY FIRST</Badge><h2 className="mt-5 max-w-xl text-3xl font-black tracking-tight sm:text-4xl">Designed so the election is about the choice, not the identity.</h2><p className="mt-5 max-w-xl leading-7 text-slate-300">The frontend separates the eligibility journey from ballot presentation. In production, the backend should enforce authorization, one-vote constraints and separate ballot storage.</p></div><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-1"><SecurityItem icon={<ShieldCheck/>} title="Verified access" text="Only roster-matched eligible students enter."/><SecurityItem icon={<Vote/>} title="Private choices" text="Ballot data should not expose voter mappings."/><SecurityItem icon={<Trophy/>} title="Controlled results" text="Results remain private until an administrator publishes them."/></div></div></section>
  </main>;
}

function HeroPreview() { return <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-5 rounded-[2.5rem] bg-blue-200/30 blur-3xl"/><div className="relative overflow-hidden rounded-4xl border border-white bg-white p-4 shadow-soft sm:p-6"><div className="flex items-center justify-between border-b border-line pb-4"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-muted">Student Council</p><p className="mt-1 text-sm font-black text-ink">Election 2026</p></div><LivePill/></div><div className="mt-6 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-[.14em] text-brand">Your ballot</p><h3 className="mt-1 text-xl font-black text-ink">Choose your representatives</h3><div className="mt-5 grid gap-3"><MiniChoice initials="AK" name="Ayaan Khan" role="CR · Class Representative" selected/><MiniChoice initials="MF" name="Maham Fatima" role="GR · General Representative"/></div></div><div className="mt-4 flex items-center justify-between rounded-2xl border border-line px-4 py-3 text-xs font-bold text-muted"><span className="flex items-center gap-2"><ShieldCheck size={15} className="text-mint"/> Identity verified</span><span>2 selections</span></div></div><div className="absolute -bottom-5 -left-4 hidden rounded-2xl border border-line bg-white p-4 shadow-soft sm:block"><p className="text-[10px] font-bold uppercase tracking-wider text-muted">Participation</p><p className="mt-1 text-xl font-black text-ink">89%</p><Progress value={89}/></div></div>; }

function MiniChoice({ initials, name, role, selected = false }: { initials: string; name: string; role: string; selected?: boolean }) { return <div className={`flex items-center gap-3 rounded-xl border p-3 ${selected ? 'border-blue-200 bg-white' : 'border-line bg-white'}`}><span className="grid size-9 place-items-center rounded-lg bg-blue-50 text-xs font-black text-brand">{initials}</span><span className="min-w-0 flex-1"><strong className="block truncate text-xs font-extrabold text-ink">{name}</strong><small className="block truncate text-[10px] font-semibold text-muted">{role}</small></span>{selected && <span className="grid size-6 place-items-center rounded-full bg-brand text-white"><Check size={13}/></span>}</div>; }

function Metric({ value, label }: { value: string; label: string }) { return <div className="border-r border-line px-4 py-2 text-center last:border-0"><strong className="block text-2xl font-black text-ink sm:text-3xl">{value}</strong><span className="mt-1 block text-[11px] font-semibold text-muted sm:text-xs">{label}</span></div>; }
function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="max-w-2xl"><span className="text-[11px] font-black uppercase tracking-[.18em] text-brand">{eyebrow}</span><h2 className="mt-3 text-3xl font-black tracking-tight text-ink sm:text-4xl">{title}</h2><p className="mt-4 leading-7 text-muted">{text}</p></div>; }
function Feature({ n, title, text }: { n: string; title: string; text: string }) { return <article className="rounded-3xl border border-line bg-white p-6 shadow-card"><span className="text-xs font-black text-brand">{n}</span><h3 className="mt-10 text-xl font-black text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-muted">{text}</p></article>; }
function SecurityItem({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="flex gap-4 rounded-2xl border border-white/10 bg-white/5 p-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white/10 text-blue-200">{icon}</span><div><strong className="text-sm font-black">{title}</strong><p className="mt-1 text-xs leading-5 text-slate-300">{text}</p></div></div>; }

function Ballot({ cr, gr, setCr, setGr, onBack, onReview }: { cr: string; gr: string; setCr: (v: string) => void; setGr: (v: string) => void; onBack: () => void; onReview: () => void }) {
  return <main className="min-h-[calc(100vh-72px)] bg-canvas"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex items-center justify-between"><Button variant="ghost" onClick={onBack}><ChevronLeft size={16}/> Exit</Button><div className="hidden sm:block"><Logo compact/></div><Badge tone="blue">{Number(Boolean(cr)) + Number(Boolean(gr))} / 2 selected</Badge></div><div className="mx-auto mt-8 max-w-3xl text-center"><LivePill/><h1 className="mt-4 text-3xl font-black tracking-tight text-ink sm:text-5xl">Make your choices.</h1><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-muted sm:text-base">Select one candidate from each category. You can review everything before the final submission.</p></div><div className="mt-10 grid gap-8 lg:grid-cols-2"><section><CategoryHeader group="CR" title="Class Representative" selected={Boolean(cr)}/><div className="grid gap-3">{candidates.filter(c => c.group === 'CR').map(c => <CandidateCard key={c.id} candidate={c} selected={cr === c.id} onSelect={() => setCr(c.id)}/>)}</div></section><section><CategoryHeader group="GR" title="General Representative" selected={Boolean(gr)}/><div className="grid gap-3">{candidates.filter(c => c.group === 'GR').map(c => <CandidateCard key={c.id} candidate={c} selected={gr === c.id} onSelect={() => setGr(c.id)}/>)}</div></section></div><div className="sticky bottom-3 mt-8 flex flex-col gap-3 rounded-2xl border border-line bg-white/95 p-3 shadow-soft backdrop-blur sm:flex-row sm:items-center sm:justify-between"><Notice>Submitted ballots are final and cannot be changed.</Notice><Button disabled={!cr || !gr} onClick={onReview} className="w-full sm:w-auto">Review ballot <ChevronRight size={16}/></Button></div></div></main>;
}

function Success({ onDone }: { onDone: () => void }) { return <main className="grid min-h-[calc(100vh-72px)] place-items-center bg-canvas px-4 py-14"><div className="w-full max-w-xl text-center"><span className="mx-auto grid size-16 place-items-center rounded-2xl bg-emerald-50 text-emerald-600 ring-8 ring-emerald-50/60"><Check size={30}/></span><Badge tone="green">Ballot recorded</Badge><h1 className="mt-5 text-4xl font-black tracking-tight text-ink">Thank you for voting.</h1><p className="mx-auto mt-3 max-w-md leading-6 text-muted">Your selections were submitted successfully. Your participation in this election is now complete.</p><div className="mt-8 grid gap-2 rounded-3xl border border-line bg-white p-4 text-left shadow-card"><Receipt label="CR selection recorded" value="1 vote"/><Receipt label="GR selection recorded" value="1 vote"/><Receipt label="Ballot status" value="Private"/></div><Button variant="secondary" className="mt-5" onClick={onDone}>Return to home</Button></div></main>; }
function Receipt({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 text-sm"><span className="flex items-center gap-2 font-semibold text-muted"><Check size={14} className="text-emerald-600"/>{label}</span><strong className="text-ink">{value}</strong></div>; }

function AdminLogin({ email, password, error, loading, onEmail, onPassword, onSubmit, onBack }: { email: string; password: string; error: string; loading: boolean; onEmail: (v: string) => void; onPassword: (v: string) => void; onSubmit: () => void; onBack: () => void }) {
  return <main className="grid min-h-screen place-items-center bg-[radial-gradient(circle_at_50%_0%,rgba(23,92,211,.14),transparent_38%),#f8fafc] px-4 py-10"><div className="w-full max-w-md"><button onClick={onBack} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-muted hover:text-ink"><ChevronLeft size={16}/> Back to voter site</button><div className="rounded-4xl border border-white bg-white p-6 shadow-soft sm:p-8"><Logo/><div className="mt-8"><Badge tone="blue">Administrator control center</Badge><h1 className="mt-4 text-3xl font-black tracking-tight text-ink">Sign in securely.</h1><p className="mt-2 text-sm leading-6 text-muted">Manage the roster, election room, candidates and controlled results.</p></div><div className="mt-7 grid gap-4"><Field label="Administrator email" type="email" value={email} onChange={e => onEmail(e.target.value)} placeholder="admin@institution.edu" autoComplete="username" disabled={loading}/><Field label="Password" type="password" value={password} onChange={e => onPassword(e.target.value)} placeholder="Enter your password" autoComplete="current-password" disabled={loading} onKeyDown={e => e.key === 'Enter' && onSubmit()}/>{error && <p className="rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700" role="alert">{error}</p>}<Button className="w-full" disabled={loading} onClick={onSubmit}>{loading ? 'Signing in…' : 'Sign in'} <ChevronRight size={16}/></Button><Notice>Credentials are checked server-side and the session uses an HttpOnly cookie. Never place admin credentials in frontend code.</Notice></div></div></div></main>;
}

function AdminShell({ page, setPage, students, setStudents, query, setQuery, csvName, setCsvName, mobileNav, setMobileNav, adminEmail, onLogout, onBack }: { page: AdminPage; setPage: (p: AdminPage) => void; students: Student[]; setStudents: React.Dispatch<React.SetStateAction<Student[]>>; query: string; setQuery: (v: string) => void; csvName: string; setCsvName: (v: string) => void; mobileNav: boolean; setMobileNav: (v: boolean) => void; adminEmail: string; onLogout: () => void; onBack: () => void }) {
  const items: { label: AdminPage; icon: React.ElementType }[] = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Students', icon: Users }, { label: 'Create Room', icon: Plus }, { label: 'Candidates', icon: ListChecks }, { label: 'Results', icon: Trophy }, { label: 'Audit Log', icon: ShieldCheck }];
  return <div className="min-h-screen bg-canvas"><aside className={`fixed inset-y-0 left-0 z-40 flex w-72 -translate-x-full flex-col border-r border-line bg-white p-4 transition md:translate-x-0 ${mobileNav ? 'translate-x-0' : ''}`}><div className="flex items-center justify-between px-2 py-2"><Logo compact/><button className="rounded-xl p-2 text-muted md:hidden" onClick={() => setMobileNav(false)} aria-label="Close navigation"><X size={18}/></button></div><p className="mt-8 px-3 text-[10px] font-black uppercase tracking-[.18em] text-muted">Control center</p><nav className="mt-3 grid gap-1">{items.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setPage(label); setMobileNav(false); }} className={`flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-bold transition ${page === label ? 'bg-blue-50 text-brand' : 'text-muted hover:bg-slate-50 hover:text-ink'}`}><Icon size={17}/>{label}</button>)}</nav><div className="mt-auto grid gap-1"><button onClick={onBack} className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-bold text-muted hover:bg-slate-50"><Vote size={17}/> Voter view</button><button onClick={onLogout} className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-bold text-muted hover:bg-slate-50"><LogOut size={17}/> Sign out</button><div className="mt-2 flex items-center gap-3 rounded-2xl bg-slate-50 p-3"><span className="grid size-9 place-items-center rounded-xl bg-ink text-xs font-black text-white">EA</span><span className="min-w-0"><strong className="block truncate text-xs font-black text-ink">Election Admin</strong><small className="block truncate text-[10px] text-muted">{adminEmail}</small></span></div></div></aside><div className="md:pl-72"><header className="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-line bg-white/90 px-4 backdrop-blur sm:px-6"><button className="rounded-xl p-2 text-muted md:hidden" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu size={20}/></button><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-brand">Admin console</p><h1 className="text-xl font-black tracking-tight text-ink">{page}</h1></div><div className="flex items-center gap-2"><Countdown/><button className="hidden rounded-xl p-2 text-muted hover:bg-slate-100 sm:block" aria-label="Settings"><Settings2 size={18}/></button></div></header>{page === 'Overview' && <AdminOverview students={students} setStudents={setStudents} csvName={csvName} setCsvName={setCsvName}/>} {page === 'Students' && <StudentsPage students={students} setStudents={setStudents} query={query} setQuery={setQuery}/>} {page === 'Create Room' && <CreateRoom/>} {page === 'Candidates' && <CandidatesPage/>} {page === 'Results' && <ResultsPage/>} {page === 'Audit Log' && <AuditPage/>}</div></div>;
}

function AdminOverview({ students, setStudents, csvName, setCsvName }: { students: Student[]; setStudents: React.Dispatch<React.SetStateAction<Student[]>>; csvName: string; setCsvName: (v: string) => void }) {
  const voted = students.filter(s => s.voted).length + 417; const eligible = students.filter(s => s.eligible).length;
  return <PageShell eyebrow="Election control" title="Overview"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><LivePill/><p className="mt-2 text-sm text-muted">Monitor the election without exposing voter choices.</p></div><Badge tone="blue">Live room · closes 13:30</Badge></div><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={<Users size={17}/>} label="Registered" value="500" detail="Current roster"/><StatCard icon={<ShieldCheck size={17}/>} label="Eligible" value={String(eligible)} detail="Roster validated"/><StatCard icon={<Vote size={17}/>} label="Votes cast" value={String(voted)} detail="Live participation"/><StatCard icon={<Clock3 size={17}/>} label="Closes in" value="03:42" detail="Today · 13:30"/></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><section className="rounded-3xl border border-line bg-white p-5 shadow-card sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-black text-ink">Participation</h2><p className="mt-1 text-xs text-muted">Votes recorded over the election window</p></div><Badge tone="blue">Live</Badge></div><div className="mt-8 flex h-48 items-end gap-2">{[38,52,64,78,92,111,126,148,170,188,214,246].map((v, i) => <div key={i} className="flex h-full flex-1 flex-col justify-end gap-2"><div className="rounded-t-lg bg-blue-100" style={{ height: `${Math.max(10, v / 2.8)}%` }}/><span className="text-center text-[9px] font-bold text-slate-400">{9+i}</span></div>)}</div></section><section className="rounded-3xl border border-line bg-white p-5 shadow-card sm:p-6"><div><h2 className="font-black text-ink">Import roster</h2><p className="mt-1 text-xs text-muted">CSV with Name, CNIC and Roll Number</p></div><div className="mt-5"><FileDrop onChange={file => { setCsvName(file.name); }}/>{csvName && <p className="mt-3 text-xs font-bold text-emerald-700">Ready: {csvName}</p>}</div></section></div><section className="mt-5 rounded-3xl border border-line bg-white p-5 shadow-card sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-black text-ink">Recent roster</h2><p className="mt-1 text-xs text-muted">Eligibility controls are available before voting starts.</p></div><Badge tone="slate">{students.length} loaded</Badge></div><div className="mt-3">{students.slice(0,5).map(s => <RosterRow key={s.id} student={s} onToggle={() => setStudents(items => items.map(x => x.id === s.id ? { ...x, eligible: !x.eligible } : x))}/>)}</div></section></PageShell>;
}

function StudentsPage({ students, setStudents, query, setQuery }: { students: Student[]; setStudents: React.Dispatch<React.SetStateAction<Student[]>>; query: string; setQuery: (v: string) => void }) {
  const filtered = useMemo(() => students.filter(s => `${s.name} ${s.roll} ${s.cnic}`.toLowerCase().includes(query.toLowerCase())), [students, query]);
  return <PageShell eyebrow="Roster management" title="Students"><div className="flex flex-col gap-3 sm:flex-row"><label className="flex h-11 flex-1 items-center gap-2 rounded-xl bg-white px-3 ring-1 ring-line"><Search size={15} className="text-muted"/><input className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-400" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name, roll or CNIC"/></label><Badge tone="green">{students.filter(s => s.eligible).length} eligible</Badge></div><section className="mt-5 rounded-3xl border border-line bg-white p-4 shadow-card sm:p-6">{filtered.length ? filtered.map(s => <RosterRow key={s.id} student={s} onToggle={() => setStudents(items => items.map(x => x.id === s.id ? { ...x, eligible: !x.eligible } : x))}/>) : <EmptyState title="No students found" description="Try a different name, Roll Number or CNIC."/>}</section></PageShell>;
}

function CreateRoom() { return <PageShell eyebrow="Election setup" title="Create election room"><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-3xl border border-line bg-white p-5 shadow-card sm:p-6"><h2 className="font-black text-ink">Election details</h2><p className="mt-1 text-xs text-muted">Information shown to voters.</p><div className="mt-5 grid gap-4"><Field label="Election title" defaultValue="Student Council Election 2026"/><div className="grid gap-4 sm:grid-cols-2"><Field label="Start time" type="datetime-local" defaultValue="2026-08-25T09:00"/><Field label="End time" type="datetime-local" defaultValue="2026-08-25T13:30"/></div></div></section><section className="rounded-3xl border border-line bg-white p-5 shadow-card sm:p-6"><h2 className="font-black text-ink">Voting rules</h2><p className="mt-1 text-xs text-muted">Fixed rules for this room.</p><div className="mt-5 grid gap-2"><Rule title="CR selection" text="Exactly one Class Representative"/><Rule title="GR selection" text="Exactly one General Representative"/><Rule title="Vote changes" text="Not allowed after submission"/></div></section><section className="rounded-3xl border border-line bg-white p-5 shadow-card sm:col-span-2 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-black text-ink">Candidate pools</h2><p className="mt-1 text-xs text-muted">Candidates available in the live room.</p></div><Badge tone="green">6 active</Badge></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Pool group="CR" title="Class Representative"/><Pool group="GR" title="General Representative"/></div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary">Save draft</Button><Button>Create room <ChevronRight size={15}/></Button></div></section></div></PageShell>; }
function Rule({ title, text }: { title: string; text: string }) { return <div className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><span><strong className="block text-sm font-bold text-ink">{title}</strong><small className="text-xs text-muted">{text}</small></span><span className="grid size-7 place-items-center rounded-full bg-emerald-50 text-emerald-600"><Check size={14}/></span></div>; }
function Pool({ group, title }: { group: 'CR' | 'GR'; title: string }) { return <div className="flex items-center gap-3 rounded-2xl border border-line p-4"><span className={`grid size-10 place-items-center rounded-xl text-xs font-black ${group === 'CR' ? 'bg-blue-50 text-blue-700' : 'bg-violet-50 text-violet-700'}`}>{group}</span><div className="flex-1"><strong className="block text-sm font-bold text-ink">{title}</strong><small className="text-xs text-muted">3 active candidates</small></div><Check size={17} className="text-emerald-600"/></div>; }
function CandidatesPage() { return <PageShell eyebrow="Candidate management" title="Candidates"><div className="grid gap-5 lg:grid-cols-2">{(['CR','GR'] as const).map(group => <section key={group} className="rounded-3xl border border-line bg-white p-5 shadow-card sm:p-6"><CategoryHeader group={group} title={group === 'CR' ? 'Class Representative' : 'General Representative'} selected={false}/><div className="grid gap-3">{candidates.filter(c => c.group === group).map(c => <div key={c.id} className="flex items-center gap-3 rounded-2xl border border-line p-3"><span className="grid size-10 place-items-center rounded-xl bg-slate-100 text-xs font-black text-slate-600">{c.initials}</span><div className="flex-1"><strong className="block text-sm font-bold text-ink">{c.name}</strong><small className="text-xs text-muted">{c.roll}</small></div><Badge tone="green">Active</Badge></div>)}</div></section>)}</div></PageShell>; }
function ResultsPage() { return <PageShell eyebrow="Controlled publication" title="Election results"><div className="grid gap-5 md:grid-cols-2"><ResultCard group="CR" winner="Ayaan Khan" votes="182" percent={43}/><ResultCard group="GR" winner="Maham Fatima" votes="176" percent={42}/></div><div className="mt-5 flex flex-col gap-4 rounded-3xl border border-line bg-white p-5 shadow-card sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-brand"><ShieldCheck size={19}/></span><div><strong className="block text-sm font-black text-ink">Results are not published</strong><p className="mt-1 text-xs text-muted">Publishing should be an explicit administrator action.</p></div></div><Button>Publish results <Trophy size={15}/></Button></div></PageShell>; }
function ResultCard({ group, winner, votes, percent }: { group: 'CR' | 'GR'; winner: string; votes: string; percent: number }) { return <article className="rounded-3xl border border-line bg-white p-6 shadow-card"><div className="flex items-center justify-between"><Badge tone={group === 'CR' ? 'blue' : 'violet'}>{group}</Badge><span className="text-xs font-bold text-muted">Leading candidate</span></div><h2 className="mt-6 text-2xl font-black text-ink">{winner}</h2><p className="mt-1 text-xs text-muted">{votes} votes · {percent}% of recorded votes</p><div className="mt-5"><Progress value={percent}/></div></article>; }
function AuditPage() { return <PageShell eyebrow="Transparency" title="Audit log"><section className="rounded-3xl border border-line bg-white p-5 shadow-card sm:p-6"><div className="grid gap-0">{auditEvents.map((event, i) => <div key={`${event.time}-${event.title}`} className="relative flex gap-4 border-b border-line py-5 last:border-0"><div className="relative"><span className={`mt-1 grid size-9 place-items-center rounded-xl ${event.tone === 'green' ? 'bg-emerald-50 text-emerald-600' : event.tone === 'blue' ? 'bg-blue-50 text-blue-600' : 'bg-violet-50 text-violet-600'}`}><ShieldCheck size={15}/></span>{i < auditEvents.length - 1 && <span className="absolute left-[17px] top-10 h-full w-px bg-line"/>}</div><div><time className="text-[10px] font-black uppercase tracking-wider text-muted">{event.time}</time><strong className="mt-1 block text-sm font-black text-ink">{event.title}</strong><p className="mt-1 text-xs leading-5 text-muted">{event.detail}</p></div></div>)}</div></section></PageShell>; }

function Review({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><span><small className="block text-xs font-semibold text-muted">{label}</small><strong className="mt-1 block text-sm font-black text-ink">{value}</strong></span><Check size={17} className="text-emerald-600"/></div>; }
function HelpStep({ n, title, text }: { n: string; title: string; text: string }) { return <div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-blue-50 text-xs font-black text-brand">{n}</span><div><strong className="text-sm font-black text-ink">{title}</strong><p className="mt-1 text-xs leading-5 text-muted">{text}</p></div></div>; }
